server:
  port: 5551

spring:
  application:
    name: cedar-product
  cloud:
    # nacos配置 此处使用nacos默认配置(本机源码启动)
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: 32705d97-6dcf-4283-89af-d5563762ea5d # 区分域，需要进一步再bootstrap中添加相关配置才会生效
  # redis配置(远程服务器)
  redis:
    cluster:
      nodes:
        - 132.232.32.7:8001
        - 132.232.32.7:8002
        - 132.232.32.7:8003
        - 132.232.32.7:8004
        - 132.232.32.7:8005
        - 132.232.32.7:8006
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 50
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    # 数据库配置(远程服务器)
  datasource:
    url: jdbc:mysql://132.232.32.7:3306/cedar?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Dr445566
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

#zk配置(远程服务器)
zk:
  curator:
    retryCount: 5 #重试次数
    elapsedTimeMs: 5000 #
    connectUrl: 132.232.32.7:2181 #zk地址
    sessionTimeOutMs: 60000 #会话超时时间
    connectionTimeOutMs: 5000 #连接超时时间

jetcache:
  # 控制台输出统计数据的间隔时间，0为不统计
  statIntervalMinutes: 15
  areaInCacheName: false # 是否加入缓存key前缀
  local:
    default:
      # 缓存类型：
      # 远程缓存支持： tair、redis
      # 本地缓存支持：linkedhashmap、caffeine
      type: caffeine
      keyConvertor: fastjson
  remote:
    default:
      type: redis.lettuce
      # 使用lettuce
      keyConvertor: fastjson # key转换器
      valueEncoder: java     # 采用java序列化和反序列化
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      # 单机版redis连接
      # host: 132.232.32.7
      # port: 6379
      # 集群版redis连接
      uri:
        # redis://密码@IP:端口/库
        - redis://132.232.32.7:8001
        - redis://132.232.32.7:8002
        - redis://132.232.32.7:8003
        - redis://132.232.32.7:8004
        - redis://132.232.32.7:8005
        - redis://132.232.32.7:8006
      readFrom: masterPreferred
