server:
  port: 8888

spring:
  application:
    name: cedar-gateway
  cloud:
    # nacos配置 此处使用nacos默认配置
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: 32705d97-6dcf-4283-89af-d5563762ea5d # 区分域，需要进一步再bootstrap中添加相关配置才会生效
    # 网关配置
    gateway:
      discovery:
        locator:
          # 默认为false，设为true开启通过微服务创建路由的功能，即可以通过微服务名访问服务
          enabled: true
      routes:
        - id: cedar-product # 路由id，全局唯一
          uri: lb://cedar-product
          predicates:
            - Path=/product/**
# gateway日志级别
logging:
  level:
    org.springframework.cloud.gateway: warn

