server:
  port: 5550

spring:
  main:
    allow-bean-definition-overriding: true #该配置针对此项目存在的多个resource都来自一个服务情况下，导致feignClient的名称相同问题
  application:
    name: cedar-bff
  cloud:
    # nacos配置 此处使用nacos默认配置
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: 32705d97-6dcf-4283-89af-d5563762ea5d # 区分域，需要进一步再bootstrap中添加相关配置才会生效

# 打开feign调用日志，需要配置类
logging:
  level:
    com.dd.service.feign: debug

